2021-02-06 19:31:08,677, DEBUG, root, Запуск Telegram-бота
2021-02-06 19:31:09,072, INFO, root, Отправлено сообщение в чат Telegram
2021-02-06 19:31:09,072, DEBUG, telegram.bot, Entering: send_message
2021-02-06 19:31:09,072, DEBUG, telegram.vendor.ptb_urllib3.urllib3.connectionpool, Starting new HTTPS connection (1): api.telegram.org
2021-02-06 19:31:09,357, DEBUG, telegram.vendor.ptb_urllib3.urllib3.connectionpool, https://api.telegram.org:443 "POST /bot1579038549:AAEQ6s75QjFhSHRQHJLRyw8jom4Spk-FySI/sendMessage HTTP/1.1" 200 604
2021-02-06 19:31:09,357, DEBUG, telegram.bot, {'message_id': 52, 'date': 1612629066, 'chat': {'id': 350758260, 'type': 'private', 'username': 'dansen95', 'first_name': 'Daniel', 'last_name': 'Sen'}, 'text': 'У вас проверили работу "dansen95__api_sp1_bot.zip"!\n\nК сожалению в работе нашлись ошибки.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1579038549, 'first_name': 'supersmartbot', 'is_bot': True, 'username': 'SuperAmazingBot'}}
2021-02-06 19:31:09,357, DEBUG, telegram.bot, Exiting: send_message
